---
- name: simple template render
  hosts: localhost
  gather_facts: no
  vars_files:
    - datavars.yml

  tasks:
    - name: build demo_render.conf
      template: src=srx-policer.j2 dest=./demo_render.conf
